apiVersion: v1
kind: Namespace
metadata:
  labels:
    cluster.x-k8s.io/provider: cluster-api
    control-plane: controller-manager
    {{- with .Values.clusterApiLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ .Values.namespace }}
