apiVersion: v1
kind: Service
metadata:
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    release.openshift.io/feature-set: CustomNoUpgrade,TechPreviewNoUpgrade
  labels:
    cluster.x-k8s.io/provider: infrastructure-aws
    clusterctl.cluster.x-k8s.io: ""
  name: capa-metrics-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: metrics
  selector:
    cluster.x-k8s.io/provider: infrastructure-aws
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    release.openshift.io/feature-set: CustomNoUpgrade,TechPreviewNoUpgrade
    service.beta.openshift.io/serving-cert-secret-name: capa-webhook-service-cert
  labels:
    cluster.x-k8s.io/provider: infrastructure-aws
    clusterctl.cluster.x-k8s.io: ""
  name: capa-webhook-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 443
      targetPort: webhook-server
  selector:
    cluster.x-k8s.io/provider: infrastructure-aws
