apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
  creationTimestamp: null
  labels:
    cluster.x-k8s.io/provider: infrastructure-aws
    clusterctl.cluster.x-k8s.io: ""
  name: capa-mutating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: capa-webhook-service
        namespace: {{ .Values.namespace }}
        path: /mutate-infrastructure-cluster-x-k8s-io-v1beta2-awsmachine
    failurePolicy: Fail
    name: mutation.awsmachine.infrastructure.cluster.x-k8s.io
    rules:
      - apiGroups:
          - infrastructure.cluster.x-k8s.io
        apiVersions:
          - v1beta2
        operations:
          - CREATE
          - UPDATE
        resources:
          - awsmachines
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: capa-webhook-service
        namespace: {{ .Values.namespace }}
        path: /mutate-infrastructure-cluster-x-k8s-io-v1beta2-awsfargateprofile
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: default.awsfargateprofile.infrastructure.cluster.x-k8s.io
    rules:
      - apiGroups:
          - infrastructure.cluster.x-k8s.io
        apiVersions:
          - v1beta2
        operations:
          - CREATE
          - UPDATE
        resources:
          - awsfargateprofiles
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: capa-webhook-service
        namespace: {{ .Values.namespace }}
        path: /mutate-infrastructure-cluster-x-k8s-io-v1beta2-awsmachinepool
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: default.awsmachinepool.infrastructure.cluster.x-k8s.io
    rules:
      - apiGroups:
          - infrastructure.cluster.x-k8s.io
        apiVersions:
          - v1beta2
        operations:
          - CREATE
          - UPDATE
        resources:
          - awsmachinepools
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: capa-webhook-service
        namespace: {{ .Values.namespace }}
        path: /mutate-infrastructure-cluster-x-k8s-io-v1beta2-awsmanagedmachinepool
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: default.awsmanagedmachinepool.infrastructure.cluster.x-k8s.io
    rules:
      - apiGroups:
          - infrastructure.cluster.x-k8s.io
        apiVersions:
          - v1beta2
        operations:
          - CREATE
          - UPDATE
        resources:
          - awsmanagedmachinepools
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: capa-webhook-service
        namespace: {{ .Values.namespace }}
        path: /mutate-infrastructure-cluster-x-k8s-io-v1beta2-rosamachinepool
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: default.rosamachinepool.infrastructure.cluster.x-k8s.io
    rules:
      - apiGroups:
          - infrastructure.cluster.x-k8s.io
        apiVersions:
          - v1beta2
        operations:
          - CREATE
          - UPDATE
        resources:
          - rosamachinepools
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: capa-webhook-service
        namespace: {{ .Values.namespace }}
        path: /mutate-bootstrap-cluster-x-k8s-io-v1beta2-eksconfig
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: default.eksconfigs.bootstrap.cluster.x-k8s.io
    rules:
      - apiGroups:
          - bootstrap.cluster.x-k8s.io
        apiVersions:
          - v1beta2
        operations:
          - CREATE
          - UPDATE
        resources:
          - eksconfig
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: capa-webhook-service
        namespace: {{ .Values.namespace }}
        path: /mutate-bootstrap-cluster-x-k8s-io-v1beta2-eksconfigtemplate
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: default.eksconfigtemplates.bootstrap.cluster.x-k8s.io
    rules:
      - apiGroups:
          - bootstrap.cluster.x-k8s.io
        apiVersions:
          - v1beta2
        operations:
          - CREATE
          - UPDATE
        resources:
          - eksconfigtemplate
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: capa-webhook-service
        namespace: {{ .Values.namespace }}
        path: /mutate-controlplane-cluster-x-k8s-io-v1beta2-awsmanagedcontrolplane
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: default.awsmanagedcontrolplanes.controlplane.cluster.x-k8s.io
    rules:
      - apiGroups:
          - controlplane.cluster.x-k8s.io
        apiVersions:
          - v1beta2
        operations:
          - CREATE
          - UPDATE
        resources:
          - awsmanagedcontrolplanes
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: capa-webhook-service
        namespace: {{ .Values.namespace }}
        path: /mutate-controlplane-cluster-x-k8s-io-v1beta2-rosacontrolplane
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: default.rosacontrolplanes.controlplane.cluster.x-k8s.io
    rules:
      - apiGroups:
          - controlplane.cluster.x-k8s.io
        apiVersions:
          - v1beta2
        operations:
          - CREATE
          - UPDATE
        resources:
          - rosacontrolplanes
    sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingAdmissionPolicy
metadata:
  name: openshift-cluster-api-protect-awscluster
  namespace: {{ .Values.namespace }}
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups:
          - infrastructure.cluster.x-k8s.io
        apiVersions:
          - '*'
        operations:
          - DELETE
        resources:
          - awsclusters
  paramKind:
    apiVersion: config.openshift.io/v1
    kind: Infrastructure
  validations:
    - expression: '!(oldObject.metadata.name == params.status.infrastructureName)'
      message: InfraCluster resources with metadata.name corresponding to the cluster infrastructureName cannot be deleted.
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: openshift-cluster-api-protect-awscluster
  namespace: {{ .Values.namespace }}
spec:
  matchResources:
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: openshift-cluster-api
  paramRef:
    name: cluster
    parameterNotFoundAction: Deny
  policyName: openshift-cluster-api-protect-awscluster
  validationActions:
    - Deny
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
  creationTimestamp: null
  labels:
    cluster.x-k8s.io/provider: infrastructure-aws
    clusterctl.cluster.x-k8s.io: ""
  name: capa-validating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: capa-webhook-service
        namespace: {{ .Values.namespace }}
        path: /validate-infrastructure-cluster-x-k8s-io-v1beta2-awsmachine
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: validation.awsmachine.infrastructure.cluster.x-k8s.io
    rules:
      - apiGroups:
          - infrastructure.cluster.x-k8s.io
        apiVersions:
          - v1beta2
        operations:
          - CREATE
          - UPDATE
        resources:
          - awsmachines
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: capa-webhook-service
        namespace: {{ .Values.namespace }}
        path: /validate-infrastructure-cluster-x-k8s-io-v1beta2-awsmachinetemplate
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: validation.awsmachinetemplate.infrastructure.cluster.x-k8s.io
    rules:
      - apiGroups:
          - infrastructure.cluster.x-k8s.io
        apiVersions:
          - v1beta2
        operations:
          - CREATE
          - UPDATE
        resources:
          - awsmachinetemplates
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: capa-webhook-service
        namespace: {{ .Values.namespace }}
        path: /validate-infrastructure-cluster-x-k8s-io-v1beta2-awsfargateprofile
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: validation.awsfargateprofile.infrastructure.cluster.x-k8s.io
    rules:
      - apiGroups:
          - infrastructure.cluster.x-k8s.io
        apiVersions:
          - v1beta2
        operations:
          - CREATE
          - UPDATE
        resources:
          - awsfargateprofiles
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: capa-webhook-service
        namespace: {{ .Values.namespace }}
        path: /validate-infrastructure-cluster-x-k8s-io-v1beta2-awsmachinepool
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: validation.awsmachinepool.infrastructure.cluster.x-k8s.io
    rules:
      - apiGroups:
          - infrastructure.cluster.x-k8s.io
        apiVersions:
          - v1beta2
        operations:
          - CREATE
          - UPDATE
        resources:
          - awsmachinepools
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: capa-webhook-service
        namespace: {{ .Values.namespace }}
        path: /validate-infrastructure-cluster-x-k8s-io-v1beta2-awsmanagedmachinepool
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: validation.awsmanagedmachinepool.infrastructure.cluster.x-k8s.io
    rules:
      - apiGroups:
          - infrastructure.cluster.x-k8s.io
        apiVersions:
          - v1beta2
        operations:
          - CREATE
          - UPDATE
        resources:
          - awsmanagedmachinepools
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: capa-webhook-service
        namespace: {{ .Values.namespace }}
        path: /validate-infrastructure-cluster-x-k8s-io-v1beta2-rosamachinepool
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: validation.rosamachinepool.infrastructure.cluster.x-k8s.io
    rules:
      - apiGroups:
          - infrastructure.cluster.x-k8s.io
        apiVersions:
          - v1beta2
        operations:
          - CREATE
          - UPDATE
        resources:
          - rosamachinepools
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: capa-webhook-service
        namespace: {{ .Values.namespace }}
        path: /validate-bootstrap-cluster-x-k8s-io-v1beta2-eksconfig
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: validation.eksconfigs.bootstrap.cluster.x-k8s.io
    rules:
      - apiGroups:
          - bootstrap.cluster.x-k8s.io
        apiVersions:
          - v1beta2
        operations:
          - CREATE
          - UPDATE
        resources:
          - eksconfig
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: capa-webhook-service
        namespace: {{ .Values.namespace }}
        path: /validate-bootstrap-cluster-x-k8s-io-v1beta2-eksconfigtemplate
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: validation.eksconfigtemplates.bootstrap.cluster.x-k8s.io
    rules:
      - apiGroups:
          - bootstrap.cluster.x-k8s.io
        apiVersions:
          - v1beta2
        operations:
          - CREATE
          - UPDATE
        resources:
          - eksconfigtemplate
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: capa-webhook-service
        namespace: {{ .Values.namespace }}
        path: /validate-controlplane-cluster-x-k8s-io-v1beta2-awsmanagedcontrolplane
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: validation.awsmanagedcontrolplanes.controlplane.cluster.x-k8s.io
    rules:
      - apiGroups:
          - controlplane.cluster.x-k8s.io
        apiVersions:
          - v1beta2
        operations:
          - CREATE
          - UPDATE
        resources:
          - awsmanagedcontrolplanes
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: capa-webhook-service
        namespace: {{ .Values.namespace }}
        path: /validate-controlplane-cluster-x-k8s-io-v1beta2-rosacontrolplane
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: validation.rosacontrolplanes.controlplane.cluster.x-k8s.io
    rules:
      - apiGroups:
          - controlplane.cluster.x-k8s.io
        apiVersions:
          - v1beta2
        operations:
          - CREATE
          - UPDATE
        resources:
          - rosacontrolplanes
    sideEffects: None
