apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: capa-system

configurations:
- namingConfiguration.yaml

resources:
- base/core-components.yaml

patches:
- patch: |-
    - op: add
      path: /metadata/annotations/service.beta.openshift.io~1serving-cert-secret-name
      value: capa-webhook-service-cert
  target:
    kind: Service
    name: capa-webhook-service
#- patch: |-
#    - op: add
#      path: /metadata/annotations/service.beta.openshift.io~1inject-cabundle
#      value: true
#    - op: delete
#      path: /metadata/annotations/cert-manager.io~1inject-ca-from
#  target:
#    annotationSelector: "cert-manager.io/inject-ca-from=capa-system/capa-serving-cert"
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/command
      value:
      - /bin/cluster-api-provider-aws-controller-manager
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: registry.redhat.io/openshift4/ose-aws-cluster-api-controllers-rhel9:__.Values.manager.image.tag__
    - op: replace
      path: /spec/template/spec/containers/0/imagePullPolicy
      value: IfNotPresent
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Deployment
    name: capa-controller-manager
- patch: |-
    - op: add
      path: /metadata/annotations/iam.amazonaws.com~1role
      value: __.Values.aws.iamRole__
  target:
    kind: ServiceAccount
    name: capa-controller-manager
- patch: |
    $patch: delete
    apiVersion: batch/v1
    kind: Issuer
    metadata:
      name: any-text
  target:
    kind: Issuer
- patch: |
    $patch: delete
    apiVersion: batch/v1
    kind: Certificate
    metadata:
      name: any-text
  target:
    kind: Certificate
